### DISCUSSION TITLE
Automatisches Setzen der Reservekapazität im undefinierten Preisbereich

### DISCUSSION THREAD

**Discussion by xlemmingx** [marq24/ha-senec-v3#117] [Show and tell]
Hallo Matthias,

zuerst mal vielen Dank für die super Integration und deine Automatisierung zur Speichernutzung mit Tibber! Ohne dich wäre das Teil nicht einmal halb so nützlich ;-)
Ich habe ziemlich genau das gleiche Setup wie du (HA, v3 duo LFP mit 10KWh Speicher, Tibber) und habe deswegen zum Jahreswechsel deine Lösung fast 1:1 übernommen. Zum Glück hatte ich (bisher?) auch nie das von dir beschrieben Problem, das nur durch einen Reset zu lösen ist.

Mir ist aufgefallen, dass in einem Zeitraum wie aktuell (=alle pow_now-Sensoren stehen auf off) trotzdem der Akku geleert wird.

Beispiel:
<img width="592" alt="2025-01-09 16_05_33-Solar   Energie – Home Assistant - Vivaldi" src="https://github.com/user-attachments/assets/3d5b6d93-7156-4f9f-9e2a-dc3ff7edc5ea" />

Ist ja generell kein Problem, weil ein Niedrigpreisfenster kommt, bevor der Preis wieder nennenswert hoch geht. Allerdings sorgt das für zusätzliche Ladeverluste und Akkualterung. Regulär gibt es ja leider keine Möglichkeit, den Speicherladestand abseits von 100% zu halten, aber wenn man das Notstrompaket hat, kann man eine Reservekapazität bis 50% setzen und damit dafür sorgen, dass der Akku nicht weiter entladen wird.

Ich habe mir dafür diese beiden Automationen ergänzt und wollte dich einmal fragen was du davon hältst. Hast du das Notstrompaket nicht, oder hast du dich aus einem anderen Grund dagegen entschieden, diese Funktionalität dafür zu zweckentfremden?

```
alias: "[POW] Set discharge Limit [ON] when neither low nor high price"
description: ""
triggers:
  - trigger: time_pattern
    minutes: "1"
    seconds: "45"
conditions: []
actions:
  - if:
      - condition: template
        value_template: |-
          {{ states('switch.ssenec_safe_charge')|lower == 'off' and (
              (states('binary_sensor.pow_now_in_low_price_phase')|lower == 'off') and
              (states('binary_sensor.pow_now_in_cheapest_phase')|lower == 'off') and
              (states('binary_sensor.pow_now_in_high_price_phase')|lower == 'off') and
              (states('binary_sensor.pow_now_in_high_price_storage_independent_phase')|lower == 'off')
            )
          }}
    then:
      - device_id: 6dd7add03eec6a3648db531269a944f1
        domain: number
        entity_id: 560f7f17d67e7eb92719418bc92665d0
        type: set_value
        value: 50
mode: single
```

```
alias: "[POW] Set discharge Limit [OFF] when low or high price"
description: ""
triggers:
  - trigger: time_pattern
    minutes: "1"
    seconds: "30"
conditions: []
actions:
  - if:
      - condition: template
        value_template: |-
          {{ 
              (states('binary_sensor.pow_now_in_low_price_phase')|lower == 'on') or
              (states('binary_sensor.pow_now_in_cheapest_phase')|lower == 'on') or
              (states('binary_sensor.pow_now_in_high_price_phase')|lower == 'on') or
              (states('binary_sensor.pow_now_in_high_price_storage_independent_phase')|lower == 'on')
          }}
    then:
      - device_id: 6dd7add03eec6a3648db531269a944f1
        domain: number
        entity_id: 560f7f17d67e7eb92719418bc92665d0
        type: set_value
        value: 0
mode: single
```

Viele Grüße
Jochen
