### DISCUSSION TITLE
"Better" house consumption data (based on AC power)

### DISCUSSION THREAD

**Discussion by marq24** [marq24/ha-senec-v3#30] [Show and tell]
As you might know the house consumption value that's provided by your Senec.HOME is not accurate, since it's based on the DC Power of the Inverters - and with that the loss of the DC->AC conversion is included in the home usage... 

In the past couple of days I spend some time in order to find alternative source of information in order to improve my home consumption value. [This might be just cosmetics, since there is no need to pay tax on the own consumption in Germany any longer - at least if you also have a battery in place].

Actually I have an additional challenge, since I have an additional Inverter. Cause of software issues, the Senec.HOME not always include the PV-Power of the additional inverter [I would had anyhow preferred, if the data of the additional inverter would not be included at the first place - but that's a different story]. So the second challenge is, that I want to know the PV-Power generated by the build in inverter(s) [I have a Hybrid duo - so there are two!].

### Challenge I: Get the AC PV-Power of the Senec Inverter(s) separately 
As [explained in detail here](https://github.com/marq24/ha-senec-v3/#connecting-the-internal-build-in-senec-inverter-hardware-to-your-lan-and-use-it-in-ha) the Senec.HOME have additional LAN connectors, that are not connected by default. When you connect them and read the data you will get actually AC-power data (so really the power you can use)!

### Challenge II: Separate the Battery Power (import & export)
But before getting too excited - the data the main inverter (called LV) providing also include the power that will be imported/exported into/from the battery. Additionally the LV-INV providing a value called `BDC LINK_Power` which seams to be the AC power that is exchanged between the (power) network and the battery.

### Challenge III: Get the AC House consumption
As already introduced, the Senec.HOME System will include the power loss of the DC->AC conversion

### Finally the code ;-)
In order to simply copy & paste the code below there are some important constraints you have to be aware. The Sensor names/entitie_ids might be different in your environment and you might just have a single inverter build into your Senec.HOME System - so please double check it with your (HA) installation!

#### Requirements
- [Connect the build-in Inverter(s) to your LAN and add them to HA](https://github.com/marq24/ha-senec-v3/#connecting-the-internal-build-in-senec-inverter-hardware-to-your-lan-and-use-it-in-ha)
- The display-name for my first inverter (in the Senec.HOME integration) is `INV-LV`
- The display-name for my second inverter (in the Senec.HOME integration) is `INV-HV`
- The display-name for my Senec.HOME main unit (in the Senec.HOME integration) is `senec`
- The AC-Power generated by my separate SMA Inverter (using the SMA-Integration) is available from `sensor.sn_3010997393_grid_power`

#### The sensors/output
| Sensor entity_id in HA | Description |
| --- | --- |
| sensor.temp_senec_solar_power | AC-PV Power generated by the Senec Inverter(s) |
| sensor.temp_total_solar_power | The "real" total generated PV power (output) by all Inverters |
| sensor.temp_house_consumption | The IMHO "real" house consumption based on all AC sources |

#### My HA `configuration.yml`
```
template:
  - unique_id: manual_power_values
    sensor:
      - name: "temp SENEC Solar Power"
        unique_id: senec_solar_power
        device_class: power
        state_class: measurement
        unit_of_measurement: 'W'
        icon: mdi:solar-power
        # WHEN the lnk_pow > 0 then this means that the power calculated for the LV
        # Inverter (lv_pow) will also include POW from the battery output!
        # Unfortunately we have some loss when getting power back from the battery, so
        # when there is NO solar power available, the lnk_pow is few watts (~10-30)
        # smaller then the lv_pow... so we calculate the lv_solar here to check, if
        # we are in such a situation (lv_solar < 0 means no solar power in lv).
        state: >
          {% set lv_pow = states('sensor.inv_lv_ac_power') | float(0) %}
          {% set hv_pow = states('sensor.inv_hv_ac_power') | float(0) %}
          {% set lnk_pow = states('sensor.inv_lv_bdc_link_power') | float(0) %}
          {% set lv_solar = lv_pow - lnk_pow %}
          {% if lv_solar > 0 %}
            {{ (hv_pow + lv_solar) | round(2, default=0) }}
          {% else %}
            {{ (hv_pow) | round(2, default=0) }}
          {% endif %}

      - name: "temp TOTAL Solar Power"
        unique_id: total_solar_power
        device_class: power
        state_class: measurement
        unit_of_measurement: 'W'
        icon: mdi:solar-power
        state: >
          {% set senec_pow = states('sensor.temp_senec_solar_power') | float(0) %}
          {% set sma_pow = states('sensor.sn_3010997393_grid_power') | float(0) %}
          {{ (senec_pow + sma_pow) | round(2, default=0) }}

      - name: "temp House consumption"
        unique_id: house_usage
        device_class: power
        state_class: measurement
        unit_of_measurement: 'W'
        icon: mdi:home-import-outline
        # IF lnk_pow < 0 then we CHARGE the BATTERY
        # IF lnk_pow > 0 then we CONSUME from the BATTERY
        # If gri_pow > 0 we are CONSUME from the GRID
        # IF gri_pow < 0 we are EXPORT power to the GRID
        # The sol_pow is the power we generate INCLUDING the power we are currently charging - so this
        # value includes the lnk_pow (but have in mind, when charing the lnk_pow is negative!) so ADD
        # the lnk_pow will result in a decrease of the final house consumption value (in charge-mode)
        # When we consume power from the battery, the lnk_pow value is positive - so ADD it will be just
        # the 'right' thing t do...
        state: >
          {% set sol_pow = states('sensor.temp_total_solar_power') | float(0) %}
          {% set gri_pow = states('sensor.senec_grid_state_power') | float(0) %}
          {% set lnk_pow = states('sensor.inv_lv_bdc_link_power') | float(0) %}
          {{ (sol_pow + gri_pow + lnk_pow) | round(2, default=0) }}

```
