### DISCUSSION TITLE
Senec and Tibber

### DISCUSSION THREAD

**Discussion by scottgoo** [marq24/ha-senec-v3#61] [Q&A]
I changed from Senec cloud to Tibber. Like to charge my senec battery when prices are low and get power from battery when prices are high.

I know the way to force a battery charge. Is there a way to pause charging then? And is there a way to block the battery from supplying the house when it is charged. Would be nice to keep the battery power for the very expensive times.

Thank you!

**Comment by bobthebuilder4711** [comment]
Sadly no.

If you know Modbus then you could engineer a device that replaces the Enfluri and would simulate energy flow from and into the grid to make your senec battery do what you want.

That would of course make the statistics on mein-senec.de or in the App totally useless. But you can always get the grid import and grid export from your digital energy meter and don't have to rely on senec for that, so Home Assistant would be able to display sane data.

But someone would have to know Modbus and would have to be willing to tinker with their senec battery.

**Reply by scottgoo** [reply]
Thanks a lot for your reply! Unfortunately I am not so big in modbus so I won’t manage to get things done this way.

**Comment by loeffelpan** [comment]
I use another "solution".
I tell an automation (not really, as I have to enable and adjust it manually regarding future prices and estimated pv energy) when to start charging to a specific soc and when to release its energy. Actually the automation is charging to that soc, stops there and restarts when soc is 10% below until release time is reached.

<img width="500" alt="image" src="https://github.com/marq24/ha-senec-v3/assets/34661317/92cd5bbd-4f5c-4b7f-8d89-d8b19fbf65fd">

```
alias: "Tibber: PV-Batterie laden"
description: ""
trigger:
  - platform: time
    id: charge
    at: input_datetime.tibber_start
  - platform: numeric_state
    entity_id:
      - sensor.senec_battery_charge_percent
    below: input_number.tibber_target_soc
    id: recharge
    value_template: "{{ state.state|float(0) + 5 }}"
  - platform: numeric_state
    entity_id:
      - sensor.senec_battery_charge_percent
    above: input_number.tibber_target_soc
    id: stop
  - platform: time
    id: disable
    at: input_datetime.tibber_end
condition:
  - condition: state
    entity_id: input_boolean.tibber_active
    state: "on"
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - charge
          - condition: numeric_state
            entity_id: sensor.senec_battery_charge_percent
            below: input_number.tibber_target_soc
        sequence:
          - service: switch.turn_on
            target:
              entity_id: switch.senec_safe_charge
            data: {}
          - service: input_boolean.turn_on
            data: {}
            target:
              entity_id: input_boolean.tibber_charging
      - conditions:
          - condition: trigger
            id:
              - recharge
        sequence:
          - condition: state
            state: "on"
            entity_id: input_boolean.tibber_charging
          - service: switch.turn_on
            target:
              entity_id: switch.senec_safe_charge
            data: {}
      - conditions:
          - condition: trigger
            id:
              - stop
        sequence:
          - condition: state
            state: "on"
            entity_id: input_boolean.tibber_charging
          - service: switch.turn_off
            target:
              entity_id: switch.senec_safe_charge
            data: {}
      - conditions:
          - condition: trigger
            id:
              - disable
        sequence:
          - service: switch.turn_off
            target:
              entity_id: switch.senec_safe_charge
            data: {}
          - service: input_boolean.turn_off
            data: {}
            target:
              entity_id:
                - input_boolean.tibber_active
                - input_boolean.tibber_charging
mode: single
```
